### ISSUE TITLE
Links on docs page go to localhost

### ISSUE THREAD

**Issue by dhasenan** [DiamondMVC/Diamond-website#11]
http://diamondmvc.org/docs under "Project Setup", for instance.

> Before we dive into the project structure, download the empty project found here.

The "here" is a link to http://127.0.0.1:8080/download

It's not the only such link.

**Comment by bausshf** [comment]
Thank you for finding that, it's a mistake on my part from just copying the urls from the browser.

Facepalm to myself.

Will have it fixed by next release of the website, which I hope to get out by today

**Comment by bausshf** [comment]
A new version of the website has been deployed and this has been fixed.
